# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffc0cb175475a4792af7f8e50dffe5ab893eb6407b1b42da4207f7ce4b82ad5b6ac510d03ed375cd9c729b6aa55a262a30b939ea0e72182a28f16652c1c74112

test:
  secret_key_base: c6544f14c9d2f8c5d51c3e78c085b3b906b09061b4485b334d9326c53716e8bb4e7ed85f20f04cd3a7f9b954c07fdc9ad0a6b26d5af9480ff635096769b2ce8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
